### PR TITLE
feat: literal filter

### PR DESCRIPTION
**Pull request by AeroNotix**
Is this something that you would be open to getting in? 

Being able to specify a list of tags to keep is much easier to use than a regex. E.g. you could have a regex match `.*` and then specify some other tags to keep explicitly, rather than trying to build a regex which doesn't match specific tags.

If open to keeping/merging, will round it out, test it, write tests.

### CODE REVIEW

**Comment by sethvargo** [comment]
I think it might be a better design to allow the user to specify `-tag-filter-any/all` multiple times, and append each to a list.

**Comment by AeroNotix** [comment]
@sethvargo I disagree, imagine the use-case and how you'd specify this. In CI or automated tooling, you'd need to first generate a list of tags you want to match, then interpolate each individual one with the flag to add it to the cli invocation.

I think the design as-is allows for a much simpler way to specify potentially many tags as well as not hinder automated uses of the tool.

**Comment by sethvargo** [comment]
Hi @AeroNotix - users should prefer the native Google Artifact Registry functionality instead of gcr-cleaner. We are only fixing bugs and security issues in gcr-cleaner now that there's a native (and free) feature in the Google Cloud product.

**Comment by AeroNotix** [comment]
Feature available until Google deletes it 😆

**Comment by AeroNotix** [comment]
(joking obvs 😄 )

**Pull request closed without merging**
