### PR TITLE
Add support for service account authentication

### PR DESCRIPTION
**Pull request by tfonfara**

### CODE REVIEW

**Comment by sethvargo** [comment]
Hi @tfonfara 

You should be able to just set `GOOGLE_APPLICATION_CREDENTIALS` and it will pick up the authentication.

**Comment by tfonfara** [comment]
> Hi @tfonfara
> 
> You should be able to just set `GOOGLE_APPLICATION_CREDENTIALS` and it will pick up the authentication.

Hi @sethvargo,

Actually this seems to have a different behavior. `GOOGLE_APPLICATION_CREDENTIALS` only accepts a file path, while this pull request is intended to use the actual contents of the file. The use case is (as suggested in the readme) to run this as GitHub Action workflow, so there the credentials typically would be stored as action secret, not as file.

**Comment by sethvargo** [comment]
Hi @tfonfara 

The preferred way to authenticate via GitHub Actions would be to use [google-github-actions/auth](https://github.com/google-github-actions/auth). You can use Workload Identity Federation or Service Account Key Export, and then anything that supports Application Default Credentials (inclugin gcr-cleaner) will pick up that authentication: https://github.com/abcxyz/lumberjack/blob/a14e9d0f14da000713ec8adf851cfeb4e808296a/.github/workflows/cleanup.yml#L68-L82

**Comment by tfonfara** [comment]
Hi @sethvargo 

Thanks, understood and actually got it working. As this doesn't seem to be documented somewhere, I would close this pr and open another one with updated documentation in the readme, if you would like?

**Comment by sethvargo** [comment]
Yea that sounds great. There's docs/github-actions which is probably the best place to document this.

**Comment by tfonfara** [comment]
Closing in favor of https://github.com/GoogleCloudPlatform/gcr-cleaner/pull/99.

**Pull request closed without merging**
