### PR TITLE
feat: add inverse-tag-filter flag

### LINKED ISSUE #49: is there a way to match everything except a constant string?
I am trying to use the following regex and it doesn't seem to work.

```"^(?\!(production|stage)$).*"```

I did some digging and found on StackOverflow that Golang has intentionally left this feature due to performance.

can we use [regexp2](https://github.com/dlclark/regexp2)?

[StackOverflow reference](https://stackoverflow.com/questions/42515407/is-there-a-way-to-match-everything-except-a-constant-string-using-go-regexp)

### PR DESCRIPTION
**Pull request by svengt**
Add inverse-tag-filter flag to make inverse
matching possible.

BREAKING CHANGES:

To check whether a tag matches the filter pattern,
we now go through all the tags. Before this, we only
checked the first tag for a match.

Closes #49

### CODE REVIEW

**Comment by sethvargo** [comment]
I'm generally not a fan of boolean variables that completely change the system's behavior. I think a better approach to https://github.com/sethvargo/gcr-cleaner/issues/49 would be to identify a regular expression library that supports look-aheads that is still actively maintained.

**Comment by powpppp** [comment]
svengt:inverse-tag-filter

**Comment by powpppp** [comment]
Pow

**Comment by svengt** [comment]
@sethvargo That would be a nice solution. Do you know any library that supports that? I'm a Python developer by trade and nog that familiar with the Go ecosystem. 

This would still leave us with the problem that the method shouldDelete only checks the first tag. Is this by design or something that you agree on changing?

**Comment by sethvargo** [comment]
I'm not familiar off the top of my head - the Go standard library regex usually suits my needs so I've never looked.

**Comment by austonpramodh** [comment]
> I'm generally not a fan of boolean variables that completely change the system's behavior. I think a better approach to #49 would be to identify a regular expression library that supports look-aheads that is still actively maintained.

I like this approach.

**Pull request closed without merging**
